# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8980c9d080ca08ce96ccdc9f4f7c6d8c8c93763074b4933bb59d603c5626b60062e1864c13c2e8c03ceecb81a29e73bb215cf239ca8bc85fb7815b6a7b2bcc5

test:
  secret_key_base: 986b12cea7b38c5e55cf69b953df38c6f8fe1ef32cfe0e765f1178a869d4b20064775bdf324de06359765cdfe6632517bb1bd52c1e4e719de0a61342bf2406a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
